### ISSUE TITLE
heads up: broken in node v19.1

### ISSUE THREAD

**Issue by ljharb** [jonschlinkert/parse-github-url#30]
I filed this as https://github.com/nodejs/node/issues/45514, so hopefully node will fix it, but I wanted you to be aware of it in case they don't, or in case node v20 will end up with the same breaking url.parse changes.

**Comment by Trott** [comment]
Should be fixed in the next release of Node.js 19 (hopefully next week). Things might change, but at this moment, my expectation is that there will be a runtime warning in Node.js 20 (release scheduled for April 2023) and then the breaking change will be introduced in Node.js 21 (release scheduled for October 2023).
